(define (square x) (* x x))
(define (attach-tag type-tag contents) (cons type-tag contents))
(define (type-tag datum)
  (if (pair? datum)
(car datum)
(error "Некорректные помеченные данные -- TYPE-TAG" datum)))
(define (contents datum)
  (if (pair? datum)
(cdr datum)
(error "Некорректные помеченные данные -- CONTENTS" datum)))